apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-servers 
  namespace: bbhnet 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-servers 
  progressDeadlineSeconds: 100
  template:
    metadata:
      labels:
        app: triton-servers 
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: tritonserver
        image: ghcr.io/ethanmarx/triton-hermes:latest
        env:
        - name: EXTRA_NV_PATHS
          value: /usr/local/nvidia/lib64:/usr/local/nvidia/bin
        command:
        - export-and-launch-triton
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics
        livenessProbe:
          failureThreshold: 30
          initialDelaySeconds: 100
          periodSeconds: 5
          httpGet:
            path: /v2/health/live
            port: http
        startupProbe:
          failureThreshold: 30
          periodSeconds: 10
          httpGet:
            path: /v2/health/ready
            port: http
        readinessProbe:
          failureThreshold: 30
          periodSeconds: 10
          httpGet:
            path: /v2/health/ready
            port: http
        resources:
          limits:
            cpu: "1"
            memory: "10G"
          requests:
            cpu: "1"
            memory: "10G"

---
apiVersion: v1
kind: Service
metadata:
  name: triton-server 
  namespace: bbhnet
spec:
  ports:
  - name: http-triton
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc-triton
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: metrics-triton
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: triton-server 
  sessionAffinity: ClientIP
  type: LoadBalancer
